cc_binary(
    name = "makemore",
    srcs = ["makemore.cc"],
    deps = [
        "@pytorch//:libtorch",
        "@abseil-cpp//absl/flags:flag",
        "@abseil-cpp//absl/strings:str_format",
    ],
)
